import type { Project, RichTextDocument } from "@/lib/domain/types";

const timestamp = "2026-04-19T12:00:00.000Z";

const sampleDocument: RichTextDocument = {
  type: "doc",
  version: 1,
  content: [
    {
      type: "paragraph",
      content: [
        {
          type: "text",
          text: "The observatory windows had learned the exact shade of dawn before Mara ever noticed how lonely the planet sounded.",
        },
      ],
    },
  ],
};

export const sampleProject: Project = {
  id: "a0100000-0000-4000-8000-000000000001",
  displayName: "Aurora Protocol",
  createdAt: timestamp,
  updatedAt: timestamp,
  title: "Aurora Protocol",
  genre: "Speculative Fiction",
  description:
    "A speculative novel workspace used to validate GlowGlobe's manuscript-first shell, contextual reference model, and planning surfaces.",
  status: "drafting",
  lifecycleState: "active",
  books: [
    {
      id: "a0200000-0000-4000-8000-000000000002",
      displayName: "Aurora Protocol",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Aurora Protocol",
      summary: "Book one manuscript draft.",
      chapters: [
        {
          id: "a0300000-0000-4000-8000-000000000003",
          displayName: "Chapter 01 · Glass Morning",
          createdAt: timestamp,
          updatedAt: timestamp,
          title: "Chapter 01 · Glass Morning",
          summary: "Mara detects the first anomaly in the observatory ring.",
          scenes: [
            {
              id: "a0400000-0000-4000-8000-000000000004",
              displayName: "Scene 01 · Opening Signal",
              createdAt: timestamp,
              updatedAt: timestamp,
              title: "Scene 01 · Opening Signal",
              summary:
                "Mara studies a fractured transmission while the observatory wakes around her, setting up the novel's tone and central mystery.",
              excerpt: [
                "Mara listened to the station breathe around her: a soft procession of vents, relays, and thermal shutters teasing daylight across the glass.",
                "On the main lens, the gas giant below reflected a pale corona back into the room, and for a moment the fractured signal on her screen looked less like noise and more like handwriting.",
                "She tagged the anomaly for the timeline, marked the scene against the observatory ring, and opened a note for the name she still could not say aloud.",
              ],
              editorDocument: sampleDocument,
              characterIds: ["a0600000-0000-4000-8000-000000000006"],
              sociumIds: ["a0900000-0000-4000-8000-000000000010"],
              locationIds: ["a1100000-0000-4000-8000-000000000012"],
              technologyEntryIds: ["a1000000-0000-4000-8000-000000000011"],
              timelineEventIds: ["a1400000-0000-4000-8000-000000000015"],
              plotThreadIds: ["a1600000-0000-4000-8000-000000000017"],
              glossaryEntryIds: ["a2100000-0000-4000-8000-000000000022"],
            },
          ],
        },
      ],
    },
  ],
  documents: [
    {
      id: "a0500000-0000-4000-8000-000000000005",
      displayName: "Manuscript Outline",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Manuscript Outline",
      kind: "note",
      content: sampleDocument,
    },
  ],
  characters: [
    {
      id: "a0600000-0000-4000-8000-000000000006",
      displayName: "Mara Vale",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Mara Vale",
      role: "Lead astronomer",
      summary: "The observatory's most gifted pattern-reader, brilliant with data and terrible at sharing uncertainty before she can prove it.",
      arc: "Moves from isolated pattern-seeker to someone willing to trust others with the truth she uncovers.",
      status: "alive",
      aliases: "M. Vale, Night Lens",
      pronouns: "she/her",
      age: "34",
      birthDate: "Cycle 184, Frostwake",
      gender: "Woman",
      speciesId: "a0800000-0000-4000-8000-000000000009",
      occupation: "Astronomer",
      sociumId: "a0900000-0000-4000-8000-000000000010",
      residence: "Helion Observatory",
      origin: "Cindervale Transfer Habitat",
      firstAppearance: "Chapter 01 · Glass Morning",
      appearance: "Lean, sleep-starved, and usually dressed in observatory greys with light-scored gloves.",
      distinguishingFeatures: "A silver burn scar on her right wrist from an array calibration accident.",
      skills: "Signal analysis, pattern recognition, orbital instrumentation, quiet endurance",
      goals: "Decode the fractured signal before the Accord loses control of the discovery.",
      fears: "Being wrong in public; triggering a conflict she cannot contain.",
      internalConflict: "She wants certainty before trust, even when secrecy isolates her.",
      externalConflict: "Political pressure from rival power blocs and the observatory's own containment rules.",
      background: "Raised in rotating research habitats, Mara learned early that data earns protection only after surviving institutional doubt.",
      personality: "Precise, observant, dryly funny, and slow to surrender control.",
      voice: "Measured, technical, and more tender than she intends when she drops her guard.",
      mannerisms: "Counts under her breath, taps rails in repeating sequences, rewinds conversations in her head before answering.",
      beliefs: "Knowledge should be stewarded responsibly, even if that makes her unpopular.",
      secrets: "She has already reproduced part of the signal privately and suspects it is responding to human attention.",
      unresolvedThreads: "Whether she can trust Iven before the Accord turns on both of them.",
      notes: "Keep her competence visible without flattening her emotional reserve.",
      quote: "Noise only looks random until someone survives it long enough to hear the grammar.",
      relationshipIds: ["a0700000-0000-4000-8000-000000000008"],
    },
    {
      id: "a0600000-0000-4000-8000-000000000007",
      displayName: "Iven Rook",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Iven Rook",
      role: "Systems pilot and recovery specialist",
      summary: "A practical field operator who reads people faster than machines and keeps finding reasons to stay near Mara's impossible problem.",
      arc: "Moves from cautious loyalist to active co-conspirator once he realizes what the signal could cost ordinary people.",
      status: "alive",
      aliases: "Rook",
      pronouns: "he/him",
      age: "38",
      birthDate: "Cycle 180, Emberturn",
      gender: "Man",
      speciesId: "a0800000-0000-4000-8000-000000000009",
      occupation: "Recovery pilot",
      sociumId: "a0900000-0000-4000-8000-000000000010",
      residence: "Helion Observatory transit deck",
      origin: "Sera perimeter flotilla",
      firstAppearance: "Chapter 02 · Static Wake",
      appearance: "Broad-shouldered, weathered by EVA work, and perpetually carrying a helmet under one arm.",
      distinguishingFeatures: "Crooked nose, low-voice laugh, and old fracture marks visible across his knuckles.",
      skills: "Shuttle piloting, salvage operations, improvisation, reading pressure in a room",
      goals: "Keep people alive while deciding whether the Accord deserves his loyalty.",
      fears: "Becoming the kind of functionary who looks away while harm gets renamed as policy.",
      internalConflict: "He wants simple loyalties in a story that keeps turning morally complex.",
      externalConflict: "Command hierarchy, contract obligations, and growing surveillance around the array.",
      background: "Iven worked border salvage and emergency response before the Accord recruited him for delicate retrieval work.",
      personality: "Steady, skeptical, warm under pressure, and harder to fool than he looks.",
      voice: "Plainspoken, wry, and disarmingly direct.",
      mannerisms: "Leans in doorways, checks exits automatically, and defuses tension with badly timed jokes.",
      beliefs: "Institutions matter only when they still protect real people.",
      secrets: "He has already been asked to report on Mara's behavior and has not decided how long he can dodge the order.",
      unresolvedThreads: "Whether his loyalty to Mara can survive the consequences of choosing her side openly.",
      notes: "Use him to surface institutional stakes without turning him into a pure exposition device.",
      quote: "You can call it containment if you want. Gravity still knows a cage when it sees one.",
      relationshipIds: ["a0700000-0000-4000-8000-000000000008"],
    },
  ],
  relationships: [
    {
      id: "a0700000-0000-4000-8000-000000000008",
      displayName: "Ally relationship between Mara and Iven",
      createdAt: timestamp,
      updatedAt: timestamp,
      sourceCharacterId: "a0600000-0000-4000-8000-000000000006",
      targetCharacterId: "a0600000-0000-4000-8000-000000000007",
      type: "ally",
      notes: "Professional trust is fragile at first, but they become each other's safest witness as the signal mystery deepens.",
    },
  ],
  species: [
    {
      id: "a0800000-0000-4000-8000-000000000009",
      displayName: "Human",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Human",
      summary: "Baseline interplanetary human lineage spread across habitats, stations, and settled systems.",
      traits: "Adaptive, socially diverse, technologically dependent, politically fragmented",
      lifespan: "Roughly 80-110 standard years depending on habitat and care access",
      cultureNotes: "More culturally varied than biologically distinct; class, station origin, and governance matter more than species-wide norms.",
      originWorld: "Sera colonial sphere",
    },
  ],
  sociums: [
    {
      id: "a0900000-0000-4000-8000-000000000010",
      displayName: "Aurora Accord",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Aurora Accord",
      type: "faction",
      summary: "A research and policy coalition trying to keep the storm-signal discovery from triggering a resource rush.",
      leadership: "Director Sel Anwen and a rotating observatory council",
      headquarters: "Helion Observatory administrative ring",
      territory: "Orbital stations above Sera and nearby listening posts",
      scope: "Interplanetary science governance",
      goals: "Contain the signal, understand its origin, and prevent militarized exploitation.",
      beliefs: "Knowledge should be stewarded carefully before it is weaponized or commercialized.",
      resources: "Observatory access, trained analysts, diplomatic standing, and signal archives",
      methods: "Quiet diplomacy, data sequestration, and tightly controlled field deployments",
      allies: "Independent observatory staff, cautious civilian ministries",
      rivals: "Private extraction syndicates and expansionist security blocs",
      publicReputation: "Respected by researchers, mistrusted by opportunists who see it as obstructionist",
      internalConflicts: "Split between radical transparency advocates and strict-containment loyalists",
      notes: "Could fracture if the signal proves sentient or economically decisive.",
    },
  ],
  technologyEntries: [
    {
      id: "a1000000-0000-4000-8000-000000000011",
      displayName: "Aurora Array",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Aurora Array",
      summary: "A signal lattice capable of translating magnetosphere turbulence into decipherable harmonic patterns.",
      ruleNotes: ["Requires planetary storms", "Degrades under sustained overload"],
    },
  ],
  locations: [
    {
      id: "a1100000-0000-4000-8000-000000000012",
      displayName: "Helion Observatory",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Helion Observatory",
      summary: "An orbital research ring where silence, light, and instrumentation define the rhythm of daily life.",
      regionName: "Upper Ring",
    },
  ],
  regions: [
    {
      id: "a1200000-0000-4000-8000-000000000013",
      displayName: "Upper Ring",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Upper Ring",
      summary: "The colder, high-visibility spine of the observatory.",
    },
  ],
  planets: [
    {
      id: "a1300000-0000-4000-8000-000000000014",
      displayName: "Sera",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Sera",
      summary: "A storm-heavy gas giant whose upper atmosphere carries the signal anomalies central to the story.",
    },
  ],
  timelineEvents: [
    {
      id: "a1400000-0000-4000-8000-000000000015",
      displayName: "First signal fracture detected",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "First signal fracture detected",
      summary: "The opening anomaly that triggers Mara's investigation.",
      sequence: 1,
    },
  ],
  corkboardCards: [
    {
      id: "a1500000-0000-4000-8000-000000000016",
      displayName: "Opening Signal",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Opening Signal",
      summary: "Introduce Mara, the observatory, and the mystery encoded in the storm noise.",
      linkedSceneId: "a0400000-0000-4000-8000-000000000004",
    },
  ],
  plotThreads: [
    {
      id: "a1600000-0000-4000-8000-000000000017",
      displayName: "Signal mystery",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Signal mystery",
      summary: "Track the meaning and origin of the fractured transmission.",
    },
  ],
  acts: [
    {
      id: "a1700000-0000-4000-8000-000000000018",
      displayName: "Act I · Discovery",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Act I · Discovery",
      summary: "Establish Mara's isolated routine and the signal that breaks it.",
      order: 1,
    },
  ],
  beats: [
    {
      id: "a1800000-0000-4000-8000-000000000019",
      displayName: "Signal fracture",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Signal fracture",
      summary: "The mystery enters the story and forces Mara to respond.",
      order: 1,
      actId: "a1700000-0000-4000-8000-000000000018",
      sceneId: "a0400000-0000-4000-8000-000000000004",
    },
  ],
  subplots: [
    {
      id: "a1900000-0000-4000-8000-000000000020",
      displayName: "Trust and disclosure",
      createdAt: timestamp,
      updatedAt: timestamp,
      name: "Trust and disclosure",
      summary: "Mara's reluctance to share what she sees becomes a source of tension.",
    },
  ],
  povMarkers: [
    {
      id: "a2000000-0000-4000-8000-000000000021",
      displayName: "Mara POV",
      createdAt: timestamp,
      updatedAt: timestamp,
      label: "Mara POV",
      summary: "Opening chapter viewpoint anchor.",
      characterId: "a0600000-0000-4000-8000-000000000006",
      sceneId: "a0400000-0000-4000-8000-000000000004",
    },
  ],
  glossaryEntries: [
    {
      id: "a2100000-0000-4000-8000-000000000022",
      displayName: "Aurora Array",
      createdAt: timestamp,
      updatedAt: timestamp,
      term: "Aurora Array",
      definition: "Instrumentation lattice used to read storm harmonics.",
    },
  ],
  loreNotes: [
    {
      id: "a2200000-0000-4000-8000-000000000023",
      displayName: "Observatory Charter",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Observatory Charter",
      summary: "The ring was commissioned to study magnetosphere behavior without direct colonial intervention.",
    },
  ],
  researchNotes: [
    {
      id: "a2300000-0000-4000-8000-000000000024",
      displayName: "Gas giant storm reference",
      createdAt: timestamp,
      updatedAt: timestamp,
      title: "Gas giant storm reference",
      summary: "Notes on cloud banding and electrical storm behavior for atmospheric scenes.",
      source: "internal planning note",
    },
  ],
  revisionSnapshots: [
    {
      id: "a2400000-0000-4000-8000-000000000025",
      displayName: "Opening pass",
      createdAt: timestamp,
      updatedAt: timestamp,
      label: "Opening pass",
      summary: "First pass of the opening chapter scaffold.",
    },
  ],
};
